import { DeleteDialog } from '@/components/confirm-dialog/delete-dialog';
import { DataTable } from '@/components/data-table/data-table';
import type { DataTableColumn } from '@/components/data-table/data-table';
import { AutoGeneratedBadge } from '@/components/expenses/auto-generated-badge';
import { ExpenseCategoryForm } from '@/components/forms/expense-category-form';
import { ExpenseForm } from '@/components/forms/expense-form';
import { Pagination } from '@/components/pagination/pagination';
import type { PaginationLink } from '@/components/pagination/pagination';
import { PaymentReceiptModal } from '@/components/payments/payment-receipt-modal';
import { SearchBox } from '@/components/search-box/search-box';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Head, router } from '@inertiajs/react';
import {
    AlertTriangle,
    CreditCard,
    FileText,
    LineChart as LineChartIcon,
    MoreVertical,
    Pencil,
    Plus,
    Tags,
    Trash2,
    WalletCards,
} from 'lucide-react';
import { useState } from 'react';
import {
    Bar,
    BarChart,
    Cell,
    Pie,
    PieChart,
    ResponsiveContainer,
    Tooltip,
    XAxis,
    YAxis,
} from 'recharts';

type ExpenseCategory = {
    id: number;
    name: string;
    description: string | null;
    expenses_count: number;
};
type Expense = {
    id: number;
    expense_category_id: number;
    title: string;
    amount: string;
    expense_date: string;
    status: string;
    source: string;
    source_period: string | null;
    vendor: string | null;
    receipt_path: string | null;
    notes: string | null;
    category: { name: string } | null;
    user: { name: string } | null;
};
type Payment = {
    id: number;
    payment_number: string;
    method: string;
    status: string;
    amount: string;
    reference: string | null;
    created_at: string;
    sale: { invoice_number: string } | null;
    customer: { display_name: string } | null;
    user: { name: string } | null;
};
type Status = { value: string; label: string };
type Source = { value: string; label: string };
type Paginated<T> = {
    data: T[];
    links: PaginationLink[];
    from: number | null;
    to: number | null;
    total: number;
};
type Props = {
    activeTab: 'revenue' | 'expenses';
    canManageExpenses: boolean;
    canManagePayments: boolean;
    expenses: Paginated<Expense> | null;
    payments: Paginated<Payment> | null;
    expenseCategories: ExpenseCategory[];
    expenseStatuses: Status[];
    expenseSources: Source[];
    total: string;
    revenueTotal: string;
    filters: {
        search: string | null;
        category_id: number | null;
        source: string | null;
        date_from: string | null;
        date_to: string | null;
    };
};

type TransactionTab = Props['activeTab'] | 'all';

const statusVariant = (status: string) => {
    if (status === 'paid' || status === 'approved' || status === 'completed')
        return 'default';
    if (status === 'rejected' || status === 'failed') return 'destructive';
    return 'secondary';
};

export default function TransactionsIndex({
    activeTab,
    canManageExpenses,
    canManagePayments,
    expenses,
    payments,
    expenseCategories,
    expenseStatuses,
    expenseSources,
    total,
    revenueTotal,
    filters,
}: Props) {
    const [deletingExpense, setDeletingExpense] = useState<Expense | null>(
        null,
    );
    const [createExpenseOpen, setCreateExpenseOpen] = useState(false);
    const [categoryOpen, setCategoryOpen] = useState(false);
    const [editingExpense, setEditingExpense] = useState<Expense | null>(null);
    const [deleting, setDeleting] = useState(false);
    const [receiptPaymentId, setReceiptPaymentId] = useState<number | null>(
        null,
    );
    const [currentTab, setCurrentTab] = useState<TransactionTab>(activeTab);
    const revenueRows = payments?.data ?? [];
    const expenseRows = expenses?.data ?? [];
    const revenueAmount = revenueRows.reduce(
        (sum, payment) => sum + Number(payment.amount),
        0,
    );
    const expenseAmount = expenseRows.reduce(
        (sum, expense) => sum + Number(expense.amount),
        0,
    );
    const netAmount = revenueAmount - expenseAmount;
    const revenueByMethod = Object.values(
        revenueRows.reduce<Record<string, { name: string; value: number }>>(
            (groups, payment) => {
                groups[payment.method] ??= { name: payment.method, value: 0 };
                groups[payment.method].value += Number(payment.amount);
                return groups;
            },
            {},
        ),
    );
    const expenseBySource = Object.values(
        expenseRows.reduce<Record<string, { name: string; value: number }>>(
            (groups, expense) => {
                groups[expense.source] ??= { name: expense.source, value: 0 };
                groups[expense.source].value += Number(expense.amount);
                return groups;
            },
            {},
        ),
    );
    const expenseByCategory = Object.values(
        expenseRows.reduce<Record<string, { name: string; value: number }>>(
            (groups, expense) => {
                const name = expense.category?.name ?? 'Uncategorized';
                groups[name] ??= { name, value: 0 };
                groups[name].value += Number(expense.amount);
                return groups;
            },
            {},
        ),
    )
        .sort((a, b) => b.value - a.value)
        .slice(0, 5);
    const combinedFlow = [
        { name: 'Revenue', value: revenueAmount },
        { name: 'Expenses', value: expenseAmount },
        { name: 'Net', value: Math.max(netAmount, 0) },
    ];
    const visualColors = [
        'var(--primary)',
        'var(--chart-2)',
        'var(--chart-3)',
        'var(--chart-4)',
        'var(--chart-5)',
    ];

    const visitTransactions = (nextFilters: Partial<Props['filters']> = {}) => {
        router.get(
            '/transactions',
            {
                tab: currentTab === 'all' ? activeTab : currentTab,
                search: filters.search ?? '',
                category_id: filters.category_id ?? '',
                source: filters.source ?? '',
                date_from: filters.date_from ?? '',
                date_to: filters.date_to ?? '',
                ...nextFilters,
            },
            { preserveScroll: true, preserveState: true, replace: true },
        );
    };

    const confirmDelete = () => {
        if (!deletingExpense) return;
        setDeleting(true);
        router.delete(`/expenses/${deletingExpense.id}`, {
            preserveScroll: true,
            onFinish: () => {
                setDeleting(false);
                setDeletingExpense(null);
            },
        });
    };

    const expenseColumns: DataTableColumn<Expense>[] = [
        {
            key: 'title',
            header: 'Expense',
            render: (expense) => (
                <div>
                    <p className="font-medium">{expense.title}</p>
                    <p className="text-xs text-muted-foreground">
                        {expense.vendor || 'No vendor'} |{' '}
                        {expense.user?.name ?? 'System'}
                    </p>
                </div>
            ),
        },
        {
            key: 'category',
            header: 'Category',
            render: (expense) => expense.category?.name ?? 'Uncategorized',
        },
        {
            key: 'source',
            header: 'Source',
            render: (expense) => <AutoGeneratedBadge source={expense.source} />,
        },
        { key: 'expense_date', header: 'Date' },
        {
            key: 'amount',
            header: 'Amount',
            render: (expense) => `${expense.amount} ETB`,
        },
        {
            key: 'status',
            header: 'Status',
            render: (expense) => (
                <Badge variant={statusVariant(expense.status)}>
                    {expense.status}
                </Badge>
            ),
        },
        {
            key: 'receipt_path',
            header: 'Receipt',
            render: (expense) =>
                expense.receipt_path ? (
                    <a
                        className="text-primary underline"
                        href={`/storage/${expense.receipt_path}`}
                        target="_blank"
                    >
                        View
                    </a>
                ) : (
                    <span className="text-muted-foreground">None</span>
                ),
        },
        {
            key: 'actions',
            header: '',
            className: 'text-right',
            render: (expense) =>
                expense.source === 'manual' ? (
                    <div className="flex justify-end gap-2">
                        <Button
                            type="button"
                            variant="outline"
                            size="icon"
                            onClick={() => setEditingExpense(expense)}
                            aria-label={`Edit ${expense.title}`}
                        >
                            <Pencil className="size-4" />
                        </Button>
                        <Button
                            type="button"
                            variant="outline"
                            size="icon"
                            onClick={() => setDeletingExpense(expense)}
                            aria-label={`Delete ${expense.title}`}
                        >
                            <Trash2 className="size-4" />
                        </Button>
                    </div>
                ) : (
                    <span className="text-xs text-muted-foreground">
                        System managed
                    </span>
                ),
        },
    ];

    const paymentColumns: DataTableColumn<Payment>[] = [
        {
            key: 'payment_number',
            header: 'Payment',
            render: (payment) => (
                <div>
                    <button
                        type="button"
                        className="font-medium text-primary underline-offset-4 hover:underline"
                        onClick={() => setReceiptPaymentId(payment.id)}
                    >
                        {payment.payment_number}
                    </button>
                    <button
                        type="button"
                        className="block text-xs text-muted-foreground underline-offset-4 hover:text-primary hover:underline"
                        onClick={() => setReceiptPaymentId(payment.id)}
                    >
                        {payment.sale?.invoice_number ?? 'No sale'}
                    </button>
                </div>
            ),
        },
        {
            key: 'customer',
            header: 'Customer',
            render: (payment) =>
                payment.customer?.display_name ?? 'Walk-in customer',
        },
        {
            key: 'amount',
            header: 'Amount',
            render: (payment) => `${payment.amount} ETB`,
        },
        {
            key: 'method',
            header: 'Method',
            render: (payment) => payment.method,
        },
        {
            key: 'status',
            header: 'Status',
            render: (payment) => (
                <Badge variant={statusVariant(payment.status)}>
                    {payment.status}
                </Badge>
            ),
        },
        {
            key: 'actions',
            header: '',
            className: 'text-right',
            render: (payment) => (
                <Button variant="outline" size="icon" asChild>
                    <a
                        href={`/payments/${payment.id}`}
                        aria-label={`View ${payment.payment_number}`}
                    >
                        <svg
                            className="size-4"
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                        >
                            <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                            />
                            <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
                            />
                        </svg>
                    </a>
                </Button>
            ),
        },
    ];

    const handleSearch = (search: string) => {
        visitTransactions({ search });
    };

    const handleDateChange = (
        dateField: 'date_from' | 'date_to',
        value: string,
    ) => {
        visitTransactions({ [dateField]: value } as Partial<Props['filters']>);
    };

    const handleCategoryChange = (value: string) => {
        visitTransactions({ category_id: value ? Number(value) : null });
    };

    const handleSourceChange = (value: string) => {
        visitTransactions({ source: value });
    };

    const handleTabChange = (nextTab: TransactionTab) => {
        setCurrentTab(nextTab);
    };

    return (
        <>
            <Head title="Transactions" />
            <div className="flex h-full flex-1 flex-col gap-6 p-4 lg:p-6">
                <div className="flex flex-wrap items-center justify-between gap-3">
                    <div className="flex items-center gap-3">
                        <div className="flex size-10 items-center justify-center rounded-md bg-primary text-primary-foreground shadow-sm">
                            <FileText className="size-5" />
                        </div>
                        <div>
                            <h1 className="text-xl font-semibold">
                                Transactions
                            </h1>
                            <p className="text-sm text-muted-foreground">
                                Track all business expenses and revenue in one
                                place.
                            </p>
                        </div>
                    </div>
                    {canManageExpenses &&
                        expenses &&
                        currentTab === 'expenses' && (
                            <div className="flex flex-wrap gap-2">
                                <Button
                                    type="button"
                                    variant="outline"
                                    onClick={() => setCategoryOpen(true)}
                                >
                                    <Tags className="size-4" />
                                    Categories
                                </Button>
                                <Button
                                    type="button"
                                    onClick={() => setCreateExpenseOpen(true)}
                                >
                                    <Plus className="size-4" />
                                    New transaction
                                </Button>
                            </div>
                        )}
                </div>

                {!canManageExpenses && !canManagePayments ? (
                    <Alert variant="destructive">
                        <AlertTriangle />
                        <AlertTitle>Business profile required</AlertTitle>
                        <AlertDescription>
                            Create your business profile before viewing
                            transactions.
                        </AlertDescription>
                    </Alert>
                ) : (
                    <div className="mb-4 flex flex-wrap items-center gap-3">
                        {canManagePayments && canManageExpenses && (
                            <Button
                                type="button"
                                variant={
                                    currentTab === 'all' ? 'default' : 'outline'
                                }
                                onClick={() => handleTabChange('all')}
                            >
                                <LineChartIcon className="mr-2 size-4" />
                                All
                            </Button>
                        )}
                        {canManagePayments && (
                            <Button
                                type="button"
                                variant={
                                    currentTab === 'revenue'
                                        ? 'default'
                                        : 'outline'
                                }
                                onClick={() => handleTabChange('revenue')}
                            >
                                <CreditCard className="mr-2 size-4" />
                                Revenue
                            </Button>
                        )}
                        {canManageExpenses && (
                            <Button
                                type="button"
                                variant={
                                    currentTab === 'expenses'
                                        ? 'default'
                                        : 'outline'
                                }
                                onClick={() => handleTabChange('expenses')}
                            >
                                <WalletCards className="mr-2 size-4" />
                                Expenses
                            </Button>
                        )}
                        {canManagePayments && canManageExpenses && (
                            <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                    <Button
                                        type="button"
                                        variant="outline"
                                        size="icon"
                                    >
                                        <MoreVertical className="size-4" />
                                    </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end">
                                    <DropdownMenuItem
                                        onSelect={() => handleTabChange('all')}
                                    >
                                        View All
                                    </DropdownMenuItem>
                                    <DropdownMenuItem
                                        onSelect={() =>
                                            handleTabChange('revenue')
                                        }
                                    >
                                        View Revenue
                                    </DropdownMenuItem>
                                    <DropdownMenuItem
                                        onSelect={() =>
                                            handleTabChange('expenses')
                                        }
                                    >
                                        View Expenses
                                    </DropdownMenuItem>
                                </DropdownMenuContent>
                            </DropdownMenu>
                        )}
                    </div>
                )}

                {currentTab === 'all' &&
                    canManagePayments &&
                    canManageExpenses &&
                    payments &&
                    expenses && (
                        <div className="grid gap-4">
                            <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_22rem]">
                                <section className="rounded-xl border bg-card p-5 shadow-sm">
                                    <div className="flex flex-wrap items-center justify-between gap-3">
                                        <div className="flex items-center gap-2">
                                            <LineChartIcon className="size-5 text-primary" />
                                            <h2 className="font-semibold">
                                                All transaction flow
                                            </h2>
                                        </div>
                                        <Badge
                                            variant={
                                                netAmount >= 0
                                                    ? 'default'
                                                    : 'destructive'
                                            }
                                        >
                                            Net {netAmount.toFixed(2)} ETB
                                        </Badge>
                                    </div>
                                    <div className="mt-5 grid gap-3 sm:grid-cols-3">
                                        <TransactionMetric
                                            label="Visible revenue"
                                            value={`${revenueAmount.toFixed(2)} ETB`}
                                        />
                                        <TransactionMetric
                                            label="Visible expenses"
                                            value={`${expenseAmount.toFixed(2)} ETB`}
                                        />
                                        <TransactionMetric
                                            label="Net position"
                                            value={`${netAmount.toFixed(2)} ETB`}
                                        />
                                    </div>
                                    <div className="mt-5 h-72 rounded-xl border bg-background p-4">
                                        <ResponsiveContainer
                                            width="100%"
                                            height="100%"
                                        >
                                            <BarChart data={combinedFlow}>
                                                <XAxis
                                                    dataKey="name"
                                                    tickLine={false}
                                                    axisLine={false}
                                                />
                                                <YAxis
                                                    tickLine={false}
                                                    axisLine={false}
                                                />
                                                <Tooltip />
                                                <Bar
                                                    dataKey="value"
                                                    radius={[10, 10, 0, 0]}
                                                >
                                                    {combinedFlow.map(
                                                        (entry) => (
                                                            <Cell
                                                                key={entry.name}
                                                                fill={
                                                                    entry.name ===
                                                                    'Revenue'
                                                                        ? 'var(--primary)'
                                                                        : entry.name ===
                                                                            'Expenses'
                                                                          ? 'var(--chart-4)'
                                                                          : 'var(--chart-2)'
                                                                }
                                                            />
                                                        ),
                                                    )}
                                                </Bar>
                                            </BarChart>
                                        </ResponsiveContainer>
                                    </div>
                                </section>

                                <section className="grid gap-4">
                                    <VisualDonut
                                        title="Revenue methods"
                                        data={revenueByMethod}
                                        colors={visualColors}
                                        empty="No revenue methods in this view."
                                    />
                                    <VisualDonut
                                        title="Expense sources"
                                        data={expenseBySource}
                                        colors={visualColors}
                                        empty="No expense sources in this view."
                                    />
                                </section>
                            </div>

                            <div className="grid gap-3 rounded-md border bg-card p-4 shadow-sm md:grid-cols-[minmax(0,1fr)_10rem_10rem]">
                                <SearchBox
                                    defaultValue={filters.search ?? ''}
                                    placeholder="Search transactions..."
                                    onSearch={handleSearch}
                                />
                                <input
                                    type="date"
                                    value={filters.date_from ?? ''}
                                    onChange={(event) =>
                                        handleDateChange(
                                            'date_from',
                                            event.target.value,
                                        )
                                    }
                                    className="h-10 rounded-md border border-input bg-background px-3 text-sm"
                                />
                                <input
                                    type="date"
                                    value={filters.date_to ?? ''}
                                    onChange={(event) =>
                                        handleDateChange(
                                            'date_to',
                                            event.target.value,
                                        )
                                    }
                                    className="h-10 rounded-md border border-input bg-background px-3 text-sm"
                                />
                            </div>
                        </div>
                    )}

                {currentTab === 'revenue' && payments && (
                    <div className="grid gap-4">
                        <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_20rem]">
                            <section className="rounded-xl border bg-card p-5 shadow-sm">
                                <div className="flex items-center gap-2">
                                    <LineChartIcon className="size-5 text-primary" />
                                    <h2 className="font-semibold">
                                        Revenue snapshot
                                    </h2>
                                </div>
                                <div className="mt-5 grid gap-3 sm:grid-cols-3">
                                    <TransactionMetric
                                        label="Filtered revenue"
                                        value={`${revenueTotal} ETB`}
                                    />
                                    <TransactionMetric
                                        label="Visible payments"
                                        value={String(revenueRows.length)}
                                    />
                                    <TransactionMetric
                                        label="Average receipt"
                                        value={`${averageAmount(revenueRows).toFixed(2)} ETB`}
                                    />
                                </div>
                            </section>
                            <VisualDonut
                                title="Revenue methods"
                                data={revenueByMethod}
                                colors={visualColors}
                                empty="No revenue methods in this view."
                            />
                        </div>
                        <div className="grid gap-3 rounded-md border bg-card p-4 shadow-sm md:grid-cols-[minmax(0,1fr)_12rem_11rem_10rem_10rem]">
                            <SearchBox
                                defaultValue={filters.search ?? ''}
                                placeholder="Search payment, reference, or invoice..."
                                onSearch={handleSearch}
                            />
                            <input
                                type="date"
                                value={filters.date_from ?? ''}
                                onChange={(event) =>
                                    handleDateChange(
                                        'date_from',
                                        event.target.value,
                                    )
                                }
                                className="h-10 rounded-md border border-input bg-background px-3 text-sm"
                            />
                            <input
                                type="date"
                                value={filters.date_to ?? ''}
                                onChange={(event) =>
                                    handleDateChange(
                                        'date_to',
                                        event.target.value,
                                    )
                                }
                                className="h-10 rounded-md border border-input bg-background px-3 text-sm"
                            />
                        </div>

                        <div className="flex items-center justify-between rounded-md border bg-card p-4 shadow-sm">
                            <div>
                                <p className="text-sm text-muted-foreground">
                                    Total revenue
                                </p>
                                <p className="text-2xl font-semibold">
                                    {revenueTotal} ETB
                                </p>
                            </div>
                            <CreditCard className="size-8 text-primary" />
                        </div>

                        <DataTable
                            columns={paymentColumns}
                            data={payments.data}
                            rowKey={(payment) => payment.id}
                            emptyMessage="No payments yet. Payments will appear after POS checkout."
                        />
                        <Pagination
                            links={payments.links}
                            from={payments.from}
                            to={payments.to}
                            total={payments.total}
                        />
                    </div>
                )}

                {currentTab === 'expenses' && expenses && (
                    <div className="grid gap-4">
                        <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_20rem]">
                            <section className="rounded-xl border bg-card p-5 shadow-sm">
                                <div className="flex items-center gap-2">
                                    <WalletCards className="size-5 text-primary" />
                                    <h2 className="font-semibold">
                                        Expense snapshot
                                    </h2>
                                </div>
                                <div className="mt-5 grid gap-3 sm:grid-cols-3">
                                    <TransactionMetric
                                        label="Filtered expenses"
                                        value={`${total} ETB`}
                                    />
                                    <TransactionMetric
                                        label="Visible entries"
                                        value={String(expenseRows.length)}
                                    />
                                    <TransactionMetric
                                        label="Manual entries"
                                        value={String(
                                            expenseRows.filter(
                                                (expense) =>
                                                    expense.source === 'manual',
                                            ).length,
                                        )}
                                    />
                                </div>
                                {expenseByCategory.length > 0 && (
                                    <div className="mt-5 space-y-3">
                                        {expenseByCategory.map((item) => (
                                            <div key={item.name}>
                                                <div className="flex justify-between text-xs">
                                                    <span>{item.name}</span>
                                                    <span className="text-muted-foreground">
                                                        {item.value.toFixed(2)}{' '}
                                                        ETB
                                                    </span>
                                                </div>
                                                <div className="mt-1.5 h-2 rounded-full bg-muted">
                                                    <div
                                                        className="h-2 rounded-full bg-primary"
                                                        style={{
                                                            width: `${Math.max((item.value / Math.max(...expenseByCategory.map((entry) => entry.value), 1)) * 100, 6)}%`,
                                                        }}
                                                    />
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </section>
                            <VisualDonut
                                title="Expense sources"
                                data={expenseBySource}
                                colors={visualColors}
                                empty="No expense sources in this view."
                            />
                        </div>
                        <div className="grid gap-3 rounded-md border bg-card p-4 shadow-sm md:grid-cols-[minmax(0,1fr)_12rem_11rem_10rem_10rem]">
                            <SearchBox
                                defaultValue={filters.search ?? ''}
                                placeholder="Search title, vendor, category..."
                                onSearch={handleSearch}
                            />
                            <select
                                value={filters.category_id ?? ''}
                                onChange={(event) =>
                                    handleCategoryChange(event.target.value)
                                }
                                className="h-10 rounded-md border border-input bg-background px-3 text-sm"
                            >
                                <option value="">All categories</option>
                                {expenseCategories.map((category) => (
                                    <option
                                        key={category.id}
                                        value={category.id}
                                    >
                                        {category.name}
                                    </option>
                                ))}
                            </select>
                            <select
                                value={filters.source ?? ''}
                                onChange={(event) =>
                                    handleSourceChange(event.target.value)
                                }
                                className="h-10 rounded-md border border-input bg-background px-3 text-sm"
                            >
                                <option value="">All sources</option>
                                {expenseSources.map((source) => (
                                    <option
                                        key={source.value}
                                        value={source.value}
                                    >
                                        {source.label}
                                    </option>
                                ))}
                            </select>
                            <input
                                type="date"
                                value={filters.date_from ?? ''}
                                onChange={(event) =>
                                    handleDateChange(
                                        'date_from',
                                        event.target.value,
                                    )
                                }
                                className="h-10 rounded-md border border-input bg-background px-3 text-sm"
                            />
                            <input
                                type="date"
                                value={filters.date_to ?? ''}
                                onChange={(event) =>
                                    handleDateChange(
                                        'date_to',
                                        event.target.value,
                                    )
                                }
                                className="h-10 rounded-md border border-input bg-background px-3 text-sm"
                            />
                        </div>

                        <div className="flex items-center justify-between rounded-md border bg-card p-4 shadow-sm">
                            <div>
                                <p className="text-sm text-muted-foreground">
                                    Filtered total
                                </p>
                                <p className="text-2xl font-semibold">
                                    {total} ETB
                                </p>
                            </div>
                            <WalletCards className="size-8 text-primary" />
                        </div>

                        <DataTable
                            columns={expenseColumns}
                            data={expenses.data}
                            rowKey={(expense) => expense.id}
                            emptyMessage="No expenses match the current filters."
                        />
                        <Pagination
                            links={expenses.links}
                            from={expenses.from}
                            to={expenses.to}
                            total={expenses.total}
                        />
                    </div>
                )}
            </div>

            <DeleteDialog
                open={Boolean(deletingExpense)}
                onOpenChange={(open) => !open && setDeletingExpense(null)}
                itemLabel={deletingExpense?.title ?? 'this transaction'}
                onConfirm={confirmDelete}
                processing={deleting}
            />

            {canManageExpenses && (
                <Dialog
                    open={createExpenseOpen}
                    onOpenChange={setCreateExpenseOpen}
                >
                    <DialogContent className="max-w-2xl">
                        <DialogHeader>
                            <DialogTitle>New transaction</DialogTitle>
                        </DialogHeader>
                        <ExpenseForm
                            expense={null}
                            categories={expenseCategories}
                            statuses={expenseStatuses}
                            onSuccess={() => setCreateExpenseOpen(false)}
                        />
                    </DialogContent>
                </Dialog>
            )}

            {canManageExpenses && (
                <Dialog
                    open={Boolean(editingExpense)}
                    onOpenChange={(open) => !open && setEditingExpense(null)}
                >
                    <DialogContent className="max-w-2xl">
                        <DialogHeader>
                            <DialogTitle>Edit transaction</DialogTitle>
                        </DialogHeader>
                        <ExpenseForm
                            expense={editingExpense}
                            categories={expenseCategories}
                            statuses={expenseStatuses}
                            onSuccess={() => setEditingExpense(null)}
                        />
                    </DialogContent>
                </Dialog>
            )}

            {canManageExpenses && (
                <Dialog open={categoryOpen} onOpenChange={setCategoryOpen}>
                    <DialogContent>
                        <DialogHeader>
                            <DialogTitle>New transaction category</DialogTitle>
                        </DialogHeader>
                        <ExpenseCategoryForm
                            category={null}
                            onSuccess={() => setCategoryOpen(false)}
                        />
                    </DialogContent>
                </Dialog>
            )}

            <PaymentReceiptModal
                paymentId={receiptPaymentId}
                open={receiptPaymentId !== null}
                onOpenChange={(open) => !open && setReceiptPaymentId(null)}
            />
        </>
    );
}

function TransactionMetric({ label, value }: { label: string; value: string }) {
    return (
        <div className="rounded-xl border bg-background p-4">
            <p className="text-xs text-muted-foreground">{label}</p>
            <p className="mt-2 text-lg font-semibold">{value}</p>
        </div>
    );
}

function VisualDonut({
    title,
    data,
    colors,
    empty,
}: {
    title: string;
    data: Array<{ name: string; value: number }>;
    colors: string[];
    empty: string;
}) {
    return (
        <section className="rounded-xl border bg-card p-5 shadow-sm">
            <h2 className="font-semibold">{title}</h2>
            {data.length > 0 ? (
                <ResponsiveContainer width="100%" height={210}>
                    <PieChart>
                        <Pie
                            data={data}
                            dataKey="value"
                            nameKey="name"
                            innerRadius={48}
                            outerRadius={78}
                            paddingAngle={4}
                        >
                            {data.map((entry, index) => (
                                <Cell
                                    key={entry.name}
                                    fill={colors[index % colors.length]}
                                />
                            ))}
                        </Pie>
                        <Tooltip />
                    </PieChart>
                </ResponsiveContainer>
            ) : (
                <div className="mt-4 rounded-xl border border-dashed bg-muted/20 p-8 text-center text-sm text-muted-foreground">
                    {empty}
                </div>
            )}
        </section>
    );
}

function averageAmount(rows: Array<{ amount: string }>) {
    if (rows.length === 0) return 0;
    return rows.reduce((sum, row) => sum + Number(row.amount), 0) / rows.length;
}

TransactionsIndex.layout = {
    breadcrumbs: [
        { title: 'Dashboard', href: '/dashboard' },
        { title: 'Transactions', href: '/transactions' },
    ],
};
