import { LegalPage  } from '@/components/landing/legal-page';
import type {LegalSection} from '@/components/landing/legal-page';

const sections: LegalSection[] = [
    { id: 'information-we-collect', title: 'Information We Collect', paragraphs: ['We may collect information you provide directly when creating or using a BizTrack account.'], bullets: ['Account information: full name, email address, phone number, password and authentication information, business name, type, address, contact information, logo, and other information you choose to provide.', 'Business data: products, categories, inventory quantities, prices, sales records, expenses, customer and employee information, payment-related records, reports, and subscription information.', 'You are responsible for having appropriate rights and permissions to enter customer or employee information into BizTrack.'] },
    { id: 'how-we-use-your-information', title: 'How We Use Your Information', paragraphs: ['We use information to provide, maintain, and improve BizTrack. We do not use your business information for unrelated purposes unless permitted by law or you have given appropriate permission.'], bullets: ['Creating and managing accounts and providing business-management functionality', 'Processing sales, inventory, customer, employee, report, subscription, and payment-support information', 'Providing support and important service notifications', 'Improving performance and security, preventing unauthorized activity, and complying with legal requirements'] },
    { id: 'business-and-customer-data', title: 'Business and Customer Data', paragraphs: ['BizTrack allows business owners to store information about their businesses and customers. The business owner is responsible for entered information and compliance with applicable laws. BizTrack processes this information to provide requested services.'] },
    { id: 'payment-information', title: 'Payment Information', paragraphs: ['Payments for BizTrack services may be processed through third-party payment providers. BizTrack does not necessarily store complete payment-card information on its own systems. Payment providers may have their own privacy policies and terms.'] },
    { id: 'cookies', title: 'Cookies and Similar Technologies', paragraphs: ['BizTrack may use cookies or similar technologies.'], bullets: ['Keep users signed in and maintain secure sessions', 'Remember preferences and improve website functionality', 'Understand platform use and improve performance and security', 'Browser settings may control cookies; disabling some may affect functionality.'] },
    { id: 'data-security', title: 'Data Security', paragraphs: ['We take reasonable technical and organizational measures to protect information against unauthorized access, disclosure, loss, misuse, alteration, and destruction. No internet-based service can guarantee absolute security. Users must protect account credentials and not share passwords with unauthorized individuals.'] },
    { id: 'data-retention', title: 'Data Retention', paragraphs: ['We retain information as reasonably necessary to provide services, maintain business records, meet operational requirements, resolve disputes, prevent fraud or abuse, and comply with legal obligations. Retention periods vary by information type and use.'] },
    { id: 'third-party-services', title: 'Third-Party Services', paragraphs: ['BizTrack may use third-party services for payment processing, hosting, authentication, infrastructure, analytics, security, and communication. Providers may process information under their own terms and privacy policies. BizTrack does not sell personal information to third parties.'] },
    { id: 'rights-and-choices', title: 'Your Rights and Choices', paragraphs: ['Depending on applicable law, you may access, correct, update, request deletion of information, close your account, or ask how information is processed. Some information may be retained for legal or legitimate business purposes.'] },
    { id: 'children-privacy', title: "Children's Privacy", paragraphs: ['BizTrack is intended for businesses and business users and is not intentionally designed to collect personal information from children without appropriate authorization.'] },
    { id: 'changes', title: 'Changes to This Privacy Policy', paragraphs: ['We may update this policy from time to time. Significant changes may be announced through the website or application, and the updated version will show a revised Last Updated date.'] },
    { id: 'contact', title: 'Contact Us', paragraphs: ['If you have questions about this Privacy Policy or how BizTrack handles information, contact BizTrack.', 'Email: [YOUR SUPPORT EMAIL]\nPhone: [YOUR PHONE NUMBER]\nAddress: [YOUR BUSINESS ADDRESS]'] },
];
export default function PrivacyPolicy() {
 return <LegalPage title="Privacy Policy" intro={['At BizTrack, we respect your privacy and are committed to protecting information you provide when using our business management platform.', 'This Privacy Policy explains what we collect, how we use and protect it, and the choices you have. By using BizTrack, you agree to these practices.']} sections={sections} />; 
}
