import { LegalPage  } from '@/components/landing/legal-page';
import type {LegalSection} from '@/components/landing/legal-page';

const sections: LegalSection[] = [
    { id: 'about-biztrack', title: 'About BizTrack', paragraphs: ['BizTrack is a business management platform designed to help businesses manage sales, products, inventory, customers, expenses, employees, payments, reports, and business performance. Available features may depend on account, business configuration, and subscription plan.'] },
    { id: 'account-registration', title: 'Account Registration', paragraphs: ['Certain features require an account. You agree to provide accurate, up-to-date registration information.'], bullets: ['Maintain confidentiality of login credentials and protect account access', 'Keep account information accurate', 'Accept responsibility for account activity unless caused by unauthorized access outside your reasonable control', 'Notify BizTrack promptly if you believe your account has been compromised'] },
    { id: 'business-accounts', title: 'Business Accounts', paragraphs: ['If you create an account on behalf of a business, you represent that you have authority to do so. Business owners are responsible for employees, cashiers, permissions, business information, products, customers, transactions, and other associated users.'] },
    { id: 'acceptable-use', title: 'Acceptable Use', paragraphs: ['You agree to use BizTrack only for lawful business purposes.'], bullets: ['Do not use BizTrack for unlawful activity, fraud, or another person’s account without authorization', 'Do not gain unauthorized access, circumvent controls, exploit vulnerabilities, or interfere with other users', 'Do not upload malicious software or damage or disrupt the platform'] },
    { id: 'your-business-data', title: 'Your Business Data', paragraphs: ['You retain responsibility for business information entered into BizTrack. You must ensure information is accurate, that you have permission to use customer and employee information, that activities comply with law, and that users have appropriate permissions. BizTrack may process data as necessary to provide services.'] },
    { id: 'financial-information', title: 'Inventory, Sales, and Financial Information', paragraphs: ['BizTrack provides tools to record and analyze sales, inventory, expenses, revenue, and profit. We do not guarantee calculations or reports will be free from errors caused by incorrect, incomplete, or improperly entered information. Verify important information before significant decisions.'] },
    { id: 'subscriptions', title: 'Subscriptions and Payments', paragraphs: ['Some features require a paid subscription. Plans, prices, features, billing periods, and payment methods may be displayed in the application. Subscription charges must be paid for the selected plan; access may depend on successful payment; plans may change; and payment processing may be handled by third parties. Purchase-specific terms may also apply.'] },
    { id: 'free-trials', title: 'Free Trials', paragraphs: ['BizTrack may offer a free trial or promotional access. Duration and limitations will be shown where applicable. A trial does not guarantee continued free access, and promotional offers may change or end where permitted.'] },
    { id: 'service-availability', title: 'Service Availability', paragraphs: ['We aim to keep BizTrack reliable but cannot guarantee uninterrupted access. Service may be unavailable because of maintenance, updates, security issues, infrastructure or third-party interruptions, network problems, or events outside our reasonable control. We may modify, suspend, or discontinue parts of the service when reasonably necessary.'] },
    { id: 'intellectual-property', title: 'Intellectual Property', paragraphs: ['BizTrack technology, branding, interface, software, designs, logos, and content are owned by or licensed to BizTrack unless stated otherwise. You may use the platform only as permitted and may not copy, modify, distribute, sell, or reverse engineer it except where law expressly permits.'] },
    { id: 'user-content', title: 'User Content', paragraphs: ['You retain ownership of submitted business information and content, subject to rights necessary to provide the service. You grant BizTrack limited rights to store, process, transmit, and display content as required to operate the platform.'] },
    { id: 'third-party-services', title: 'Third-Party Services', paragraphs: ['BizTrack may integrate with or rely on third-party services that have separate terms and privacy policies. BizTrack is not responsible for independently operated services.'] },
    { id: 'suspension-termination', title: 'Account Suspension or Termination', paragraphs: ['BizTrack may suspend or terminate an account where reasonably necessary, including for Terms violations, unlawful activity, suspected fraud or abuse, security risk, unpaid required charges, or service misuse. We may provide notice where appropriate.'] },
    { id: 'closing-account', title: 'Closing Your Account', paragraphs: ['You may stop using BizTrack and request closure through available account or support channels. Certain information may remain where required by law, security needs, legitimate business purposes, or retention policies.'] },
    { id: 'disclaimer', title: 'Disclaimer', paragraphs: ['BizTrack is provided on an “as available” and “as is” basis to the extent permitted by law. We do not guarantee uninterrupted, error-free, or always-available service, or improved business results. BizTrack does not replace professional accounting, legal, tax, or financial advice.'] },
    { id: 'limitation-liability', title: 'Limitation of Liability', paragraphs: ['To the maximum extent permitted by applicable law, BizTrack is not responsible for indirect, incidental, special, consequential, or similar losses arising from use of the service. Nothing excludes liability that cannot legally be excluded or limited.'] },
    { id: 'changes', title: 'Changes to These Terms', paragraphs: ['We may update these Terms. Updated versions will be published on the BizTrack website or application. Continued use after effective changes means acceptance of revised Terms to the extent permitted by law.'] },
    { id: 'governing-law', title: 'Governing Law', paragraphs: ['These Terms are governed by applicable laws and regulations of the jurisdiction in which BizTrack is legally established, unless law requires otherwise.', '[INSERT APPROPRIATE JURISDICTION]'] },
    { id: 'contact', title: 'Contact Us', paragraphs: ['If you have questions about these Terms, contact BizTrack.', 'Email: [YOUR SUPPORT EMAIL]\nPhone: [YOUR PHONE NUMBER]\nAddress: [YOUR BUSINESS ADDRESS]'] },
];
export default function TermsOfService() {
 return <LegalPage title="Terms of Service" intro={['Welcome to BizTrack. These Terms of Service govern access to and use of the BizTrack website, application, and related services.', 'By creating an account or using BizTrack, you agree to these Terms. If you do not agree, you should not use the service.']} sections={sections} />; 
}
