import { Badge } from '@/components/ui/badge';
import { Boxes, RefreshCw, UserRound } from 'lucide-react';

type Props = {
    source: string;
};

export function AutoGeneratedBadge({ source }: Props) {
    if (source === 'manual') {
        return <Badge variant="outline">Manual</Badge>;
    }

    const Icon = source === 'restock' ? Boxes : source === 'payroll' ? UserRound : RefreshCw;
    const label = source === 'restock' ? 'Restock' : source === 'payroll' ? 'Payroll' : source;

    return (
        <Badge variant="secondary" className="gap-1">
            <Icon className="size-3" />
            {label}
        </Badge>
    );
}
