import { Head } from '@inertiajs/react';
import { PremiumHeader } from '@/components/landing/premium-header';
import { SiteFooter } from '@/components/landing/site-footer';

export type LegalSection = { id: string; title: string; paragraphs: string[]; bullets?: string[] };

export function LegalPage({ title, intro, sections }: { title: string; intro: string[]; sections: LegalSection[] }) {
    return <><Head title={`${title} | BizTrack`} /><main className="min-h-screen overflow-x-hidden bg-slate-50 text-slate-900"><PremiumHeader landingPage={false} />
        <section data-header-theme="hero" className="bg-emerald-950 px-4 pb-16 pt-32 text-white sm:px-5 sm:pb-20 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold uppercase tracking-[0.22em] text-emerald-300">BizTrack legal</p><h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">{title}</h1><p className="mt-5 text-sm text-emerald-50/70">Last Updated: August 14, 2026</p></div></section>
        <section data-header-theme="light" className="mx-auto grid w-full max-w-7xl gap-12 px-4 py-12 sm:px-5 lg:grid-cols-[15rem_minmax(0,1fr)] lg:px-8 lg:py-16"><aside className="hidden lg:block"><nav aria-label={`${title} table of contents`} className="sticky top-28 border-l border-emerald-200 pl-5"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-700">On this page</p><ol className="mt-4 space-y-2 text-sm text-slate-600">{sections.map((section, index) => <li key={section.id}><a className="transition-colors hover:text-emerald-700" href={`#${section.id}`}>{index + 1}. {section.title}</a></li>)}</ol></nav></aside><article className="max-w-3xl"><div className="space-y-4 text-base leading-8 text-slate-600">{intro.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="mt-12 space-y-12">{sections.map((section, index) => <section id={section.id} key={section.id} className="scroll-mt-28"><h2 className="text-2xl font-semibold tracking-tight text-slate-950">{index + 1}. {section.title}</h2><div className="mt-4 space-y-4 text-base leading-8 text-slate-600">{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul className="space-y-2 pl-5 marker:text-emerald-600">{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</div></section>)}</div></article></section><SiteFooter landingPage={false} /></main></>;
}
